export const listQuestionsForTutorSignIn = [
    {
        id: 1,
        typeForm: "phone",
        question: "Номер телефона",
        description: "Отправим уведомление для подтверждения входа",
        placeholder: "Введите номер телефона",
        nextPage: "/sign-in-tutor/confirmation",
    },
    {
        id: 2,
        typeForm: "confirmation",
        question: "Подтверждение номера телефона",
        description: "Отправили код на номер",
        placeholder: "",
        nextPage: "/sign-in-tutor/fio",
    },
    {
        id: 3,
        typeForm: "fio",
        question: "Как вас зовут?",
        description: "Пожалуйста, укажите ФИО как в паспорте",
        placeholder: "Иванов Иван Иванович",
        nextPage: "/sign-in-tutor/subjects",
    },
    {
        id: 4,
        typeForm: "subjects",
        question: "Подтверждение номера телефона",
        description: "Отправили код на номер",
        placeholder: "",
        nextPage: "/sign-in-tutor/geo",
    },
    {
        id: 5,
        typeForm: "geo",
        question: "Подтверждение номера телефона",
        description: "Отправили код на номер",
        placeholder: "",
        nextPage: "/sign-in-tutor/locations",
    },
    {
        id: 6,
        typeForm: "locations",
        question: "Подтверждение номера телефона",
        description: "Отправили код на номер",
        placeholder: "",
        nextPage: "/sign-in-tutor/photo",
    },
    {
        id: 7,
        typeForm: "photo",
        question: "Подтверждение номера телефона",
        description: "Отправили код на номер",
        placeholder: "",
        nextPage: "/sign-in-tutor/email",
    },
    {
        id: 8,
        typeForm: "email",
        question: "Подтверждение номера телефона",
        description: "Отправили код на номер",
        placeholder: "",
        nextPage: "/backoffice",
    },
  ];
  